version: 0.2

phases:
  install:
    commands:
      - echo "Installing kubectl..."
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI_FRONT=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$FRONT_IMAGE_REPO_NAME
      - REPOSITORY_URI_BACK=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$BACK_IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}
      - echo "IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building and pushing frontend image..."
      - docker buildx build --push -t $REPOSITORY_URI_FRONT:latest -t $REPOSITORY_URI_FRONT:$IMAGE_TAG ./frontend
      - echo "Building and pushing backend image..."
      - docker buildx build --push -t $REPOSITORY_URI_BACK:latest -t $REPOSITORY_URI_BACK:$IMAGE_TAG ./bookapp/bookapp

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Writing image definitions..."
      - printf '[{"name":"frontend","imageUri":"%s"},{"name":"backend","imageUri":"%s"}]' "$REPOSITORY_URI_FRONT:$IMAGE_TAG" "$REPOSITORY_URI_BACK:$IMAGE_TAG" > imagedefinitions.json

      - echo "Substituting image paths in k8s manifests..."
      - sed -i "s|416225317325.dkr.ecr.us-east-1.amazonaws.com/user30-back-repo:latest|${REPOSITORY_URI_BACK}:${IMAGE_TAG}|g" k8s-manifests.yaml
      - sed -i "s|416225317325.dkr.ecr.us-east-1.amazonaws.com/user30-front-repo:latest|${REPOSITORY_URI_FRONT}:${IMAGE_TAG}|g" k8s-manifests.yaml

      - echo "Deploying to Amazon EKS..."
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME
      - kubectl apply -f k8s-manifests.yaml
      - kubectl apply -f hpa.yaml
      - kubectl rollout status deployment/bookapp-backend
      - kubectl rollout status deployment/bookapp-frontend

artifacts:
  files:
    - imagedefinitions.json
    - k8s-manifests.yaml
    - hpa.yaml