version: 0.2

phases:
  install:
    commands:
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - aws eks update-kubeconfig \
          --region $AWS_DEFAULT_REGION \
          --name $EKS_CLUSTER_NAME

  build:
    commands:
      - kubectl apply -f k8s-manifests.yaml

  post_build:
    commands:
      - kubectl rollout restart deployment/bookapp-backend
      - kubectl rollout restart deployment/bookapp-frontend
      - kubectl get pods